theme: jekyll-theme-cayman
---
layout: post
title: Adding custom JavaScript for a specific post
category: posts
customjs:
 - http://code.jquery.com/jquery-1.4.2.min.js
 - http://assets.adobedtm.com/launch-EN1a155fe5e7534277a8bcb035d14431e9-development.min.js
---
